id: 6b31e44a3fdc4b00a026949cba234d92
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_207-Strength_of_the_Elephant-v2
  language: bo
  author: ''
  volume: {}
